### ISSUE TITLE
Cannot require request-rate-limiter

### ISSUE THREAD

**Issue by jaimeokhuysen** [eventEmitter/request-rate-limiter#13]
Hey,
I get the following error when trying to declare request-rate-limiter.
My code:
`var RateLimiter = require('request-rate-limiter')`
Error:
```
C:\node_modules\request-rate-limiter\index.mjs:1
(function (exports, require, module, __filename, __dirname) { import RequestRateLimiter from './src/RequestRateLimiter.mjs';
                                                                     ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\server.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by linaGirl** [comment]
You have to use a node version supporting the [`--experimental-modules`](https://nodejs.org/api/cli.html#cli_experimental_modules) flag because this module is written as a [Javascript module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). Node 9+ should be fine.

**Comment by jaimeokhuysen** [comment]
No, using the [--experimental-modules ](https://nodejs.org/api/cli.html#cli_experimental_modules) flag throws the same error :(
