### ISSUE TITLE
Request randomly gets `this` set to global object

### ISSUE THREAD

**Issue by TomBentleyIBM** [eventEmitter/request-rate-limiter#5]
I'm running NodeJS 4.4.5.  

The rate limiter `this` reference gets randomly set to the global object which causes this code to fail.  I'm using my own request instance as per your documentation.  This is the scenario that caused the issue.

```
 this.backoff(function() {
     executeRequest(null, config);
 }.bind(this));
```

Since the global `this` doesn't have the function `backoff` an exception will be thrown.  I've made some changes to how the `this` reference is used and my tests now work fine, no random errors.

Here are my suggested changes:

```
        /**
         * send rate limited requests
         *
         * @param <object> request configuration
         * @param <function> optional callback, if omitted
         *                   a promise is retuned
         */
        , request: asyncMethod(function(config, callback) {

            if (debug) {
                if (type.function(config)) log.debug('[%s] Got request ...', this.logId);
                else log.debug('[%s] Got request for url %s ...', this.logId, config.url);
            }

            var _this = this;

            _this.bucket.throttle(function executeRequest(err, cb) {
                if (cb) config = cb;

                if (err) {
                    // fail, it would take way too long
                    // to execute the requesz
                    if (debug) {
                        if (type.function(config)) log.info('[%s] Throttling of the request failed, max allowed waiting time of %s seconds exceeded ...', this.logId, this.maxWaitingTime);
                        else log.info('[%s] Throttling of the request on %s failed, max allowed waiting time of %s seconds exceeded ...', this.logId, config.url, this.maxWaitingTime);
                    }

                    if (type.function(config)) config(new Error('The request was not executed because it would not be scheduled within the max waiting time!'));
                    else callback(new Error('The request was not executed because it would not be scheduled within the max waiting time!'));
                }
                else {
                     // execute the request
                    if (debug) log.debug('[%s] Request on %s is firing now...', this.logId, config.url);

                    if (type.function(config)) {
                        // the user does the request

                        config(null, function backoffCB() {

                            // backoff callback called by the user if we need to back off
                            _this.backoff(function() {
                                executeRequest(null, config);
                            });
                        });
                    }
                    else _this._request(config, callback);
                }
            });
        })
```

I also tested these changes with the built-in request case and it worked fine.  If there is anything else I can help with please let me know, hopefully this can get resolved quickly.  Thanks.

**Comment by linaGirl** [comment]
do you have a stacktrace for the error. It's not very obvious to me what the exact problem is since all functions are bound to the local scope. some code of yours would also be helpful for finding the exact problem.

**Comment by TomBentleyIBM** [comment]
As I said, the failure is pretty random (took 8 runs to reproduce) so I don't know the exact cause.  I'll give you what I can.

Here is the setup

```
var limiter = new RateLimiter({
    rate: 300,              // requests per interval,
                            // defaults to 60
    interval: 60,           // interval for the rate, x
                            // requests per interval,
                            // defaults to 60
    backoffCode: 429,       // back off when this status is
                            // returned, defaults to 429
    backoffTime: 10,        // back off for n seconds,
                            // defaults to rate/5
    maxWaitingTime: 300     // return errors for requests
                            // that will have to wait for
                            // n seconds or more. defaults
                            // to 5 minutes
});
```


```
16 13:15:44.904 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.904 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.906 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.906 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.907 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.907 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.909 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.910 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.911 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.912 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.912 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.913 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.913 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.914 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.914 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.914 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.915 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.916 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.916 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.918 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.919 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.919 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.919 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.920 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.922 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.923 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.924 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.924 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.926 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.926 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.929 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.930 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.931 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.931 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.932 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.932 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.933 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.934 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.934 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.935 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.935 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.935 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.936 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.936 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.937 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.937 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
16 13:15:44.937 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 98:48,             >>> [0] Got request ...
16 13:15:44.938 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [0] Request on undefined is firing now...
--> Enter backoff : function () { [native code] }
16 13:15:45.479 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 148:48,            >>> [0] The peer instructed us to back off, backing off now ...
16 13:15:45.480 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 158:32,            >>> [0] Pausing the leaky bucket for 10 seconds ...
<-- Exit backoff
16 13:15:45.482 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [undefined] Request on undefined is firing now...
--> Enter backoff : function () { [native code] }
16 13:15:45.514 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 148:48,            >>> [0] The peer instructed us to back off, backing off now ...
<-- Exit backoff
16 13:15:45.516 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [undefined] Request on undefined is firing now...
--> Enter backoff : function () { [native code] }
16 13:15:45.647 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 148:48,            >>> [0] The peer instructed us to back off, backing off now ...
<-- Exit backoff
16 13:15:45.648 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [undefined] Request on undefined is firing now...
--> Enter backoff : function () { [native code] }
16 13:15:45.669 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 148:48,            >>> [0] The peer instructed us to back off, backing off now ...
<-- Exit backoff
16 13:15:45.671 > nm:\request-rate-limiter\lib\RequestRateLimiter.js 119:36,            >>> [undefined] Request on undefined is firing now...
--> Enter backoff : function () { [native code] }
2017-06-16T17:15:45.890Z - error: uncaughtException: this.backoff is not a function 
{ date: 'Fri Jun 16 2017 13:15:45 GMT-0400 (Eastern Daylight Time)',
  process: 
   { pid: 11272,
     uid: null,
     gid: null,
     cwd: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection',
     execPath: 'C:\\Program Files\\IBM\\node\\node.exe',
     version: 'v4.4.5',
     argv: 
      [ 'C:\\Program Files\\IBM\\node\\node.exe',
        'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\app.js' ],
     memoryUsage: { rss: 80314368, heapTotal: 55920720, heapUsed: 48190808 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 147230.3258041 },
  trace: 
   [ { column: 34,
       file: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request-rate-limiter\\lib\\RequestRateLimiter.js',
       function: null,
       line: 127,
       method: null,
       native: false },
     { column: 21,
       file: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\lib\\datafetchers\\xxx-datafetcher.js',
       function: 'Request._callback',
       line: 518,
       method: '_callback',
       native: false },
     { column: 22,
       file: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request\\request.js',
       function: 'Request.self.callback',
       line: 187,
       method: 'callback',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitTwo',
       line: 87,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Request.emit',
       line: 172,
       method: 'emit',
       native: false },
     { column: 10,
       file: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request\\request.js',
       function: null,
       line: 1048,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 77,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Request.emit',
       line: 169,
       method: 'emit',
       native: false },
     { column: 12,
       file: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request\\request.js',
       function: null,
       line: 969,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'emitNone',
       line: 72,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Gunzip.emit',
       line: 166,
       method: 'emit',
       native: false },
     { column: 12,
       file: '_stream_readable.js',
       function: 'endReadableNT',
       line: 913,
       method: null,
       native: false },
     { column: 28,
       file: 'C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\newrelic\\lib\\transaction\\tracer\\index.js',
       function: 'wrapped',
       line: 183,
       method: null,
       native: false },
     { column: 9,
       file: 'node.js',
       function: 'nextTickCallbackWith2Args',
       line: 442,
       method: null,
       native: false },
     { column: 17,
       file: 'node.js',
       function: 'process._tickDomainCallback [as _tickCallback]',
       line: 397,
       method: '_tickDomainCallback [as _tickCallback]',
       native: false } ],
  stack: 
   [ 'TypeError: this.backoff is not a function',
     '    at C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request-rate-limiter\\lib\\RequestRateLimiter.js:127:34',
     '    at Request._callback (C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\lib\\datafetchers\\xxxx-datafetcher.js:518:21)',
     '    at Request.self.callback (C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request\\request.js:187:22)',
     '    at emitTwo (events.js:87:13)',
     '    at Request.emit (events.js:172:7)',
     '    at Request.<anonymous> (C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request\\request.js:1048:10)',
     '    at emitOne (events.js:77:13)',
     '    at Request.emit (events.js:169:7)',
     '    at Gunzip.<anonymous> (C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\request\\request.js:969:12)',
     '    at emitNone (events.js:72:20)',
     '    at Gunzip.emit (events.js:166:7)',
     '    at endReadableNT (_stream_readable.js:913:12)',
     '    at wrapped (C:\\dev\\GitHub\\wasm-node-services\\sma-collection\\node_modules\\newrelic\\lib\\transaction\\tracer\\index.js:183:28)',
     '    at nextTickCallbackWith2Args (node.js:442:9)',
     '    at process._tickDomainCallback [as _tickCallback] (node.js:397:17)' ] }
```

**Comment by linaGirl** [comment]
thanks for the information. 

since i don't have a testcase for checking the problem myself i changed the only thing i'm not 100% sure about and released a small update. 

can you please try again with version v.1.0.2?

**Comment by TomBentleyIBM** [comment]
I picked up your new version, so far it seems to be working fine.  I'll continue testing throughout the day, if I don't encounter any issues I'll close this.  Thanks for your fast response to this issue.

**Comment by TomBentleyIBM** [comment]
At this point I haven't encountered any new issues so I'm closing this.
